substitutions:
  _IMAGE_URI: ""

steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-f", "web/Dockerfile", "-t", "${_IMAGE_URI}", "web"]

images:
  - "${_IMAGE_URI}"

options:
  logging: CLOUD_LOGGING_ONLY
